name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the desired Node.js version
          cache: 'yarn'      # Enable Yarn caching

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Debug installed packages
        run: |
          yarn list --pattern @anthony0030/bootwind
          ls -la node_modules/@anthony0030/bootwind
        shell: bash

      - name: Precompile Tailwind
        run: yarn build # Or your specific Tailwind build command
        env:
          RAILS_ENV: test

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          RAILS_ENV: test
        run: |
          bin/rails test:prepare
          bin/rails db:test:prepare
          bin/rails test
      # - uses: hatchboxio/github-hatchbox-deploy-action@v2
      #   with:
      #     deploy_key: ${{ secrets.HATCHBOX_DEPLOY_KEY }}
